version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    network_mode: default
    depends_on:
      - redis
      - postgres
  redis:
    container_name: redis
    image: redis:5
    network_mode: default
  postgres:
    container_name: postgres
    image: postgres:10.4-alpine
    network_mode: default
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data
volumes:
  postgres-data:
